# Generated by Django 4.0.6 on 2022-07-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('consignee', models.CharField(max_length=100)),
                ('date_in', models.DateField(auto_now_add=True)),
                ('time_in', models.TimeField(auto_now_add=True)),
                ('vehicle_in', models.CharField(max_length=100)),
                ('ex_vessel', models.CharField(max_length=100)),
                ('shipper', models.CharField(max_length=100)),
                ('vehicle_out', models.CharField(max_length=100)),
                ('to_vessel', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('status_out', models.CharField(max_length=100)),
                ('condition_out', models.CharField(max_length=100)),
                ('date_out', models.DateField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('arr_date', models.DateField()),
                ('to_date', models.DateField(auto_now_add=True)),
                ('off_date', models.DateField()),
                ('off_hire', models.CharField(max_length=100)),
                ('st_out', models.CharField(max_length=100)),
                ('rep_date', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('estinumb', models.CharField(max_length=100)),
                ('dt_dstf', models.CharField(max_length=100)),
                ('dt_stf', models.CharField(max_length=100)),
                ('on_date', models.CharField(max_length=100)),
                ('condstat', models.CharField(max_length=100)),
                ('in_tran', models.BooleanField(default=False)),
                ('out_tran', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=500)),
                ('out_description', models.CharField(max_length=500)),
                ('prefix', models.CharField(max_length=100)),
                ('s_code', models.CharField(max_length=100)),
                ('in_apr', models.CharField(max_length=100)),
                ('out_apr', models.CharField(max_length=100)),
                ('dms', models.CharField(max_length=100)),
                ('no', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=100)),
                ('nic', models.CharField(max_length=100)),
                ('rel', models.CharField(max_length=100)),
                ('res', models.CharField(max_length=100)),
                ('rsv', models.CharField(max_length=100)),
                ('vent', models.CharField(max_length=100)),
                ('ton', models.CharField(max_length=100)),
                ('manuf', models.CharField(max_length=100)),
                ('inp', models.CharField(max_length=100)),
                ('outp', models.CharField(max_length=100)),
                ('codespc', models.CharField(max_length=100)),
                ('datespc', models.CharField(max_length=100)),
            ],
        ),
    ]
