# Generated by Django 4.0.6 on 2022-07-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers',
            name='ex_vessel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='containers',
            name='vehicle_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
