# Generated by Django 4.0.6 on 2022-07-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_containers_amount_alter_containers_arr_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers',
            name='in_tran',
            field=models.BooleanField(default=True),
        ),
    ]
