# Generated by Django 4.0.6 on 2022-07-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_vessels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('addLine1', models.CharField(blank=True, max_length=100, null=True)),
                ('addLine2', models.CharField(blank=True, max_length=100, null=True)),
                ('addLine3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
