# Generated by Django 4.0.6 on 2022-07-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_containers_bl_number_containers_c_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containers',
            name='p_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
