# Generated by Django 4.0.6 on 2022-07-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_containers_p_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='containers',
            name='rel_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
