# Generated by Django 4.0.6 on 2022-07-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_remove_containers_amount_remove_containers_codespc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containers',
            name='reservation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='containers',
            name='reserved_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='containers',
            name='reserved_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
